name = "Twilight Sparkle"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a7b778aa06e5dc9aceff69d3a056bdbc1e6731730f3ba11c2d751560879c418"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
